### ISSUE TITLE
Make a new release with filtering support

### ISSUE THREAD

**Issue by christophercr** [btroncone/ngrx-store-logger#17]
Hi,

I've seen that the filtering capability has been recently added  (#16). It would be nice to have a new release including this feature.

Do you know when can this be released?

**Comment by isaacplmann** [comment]
@btroncone It's been a couple months since this was posted.  Any plan for making another release to npm?

**Comment by btroncone** [comment]
Apologies, I've been super busy and this slipped my mind. I will get a new release out tonight, I promise. 👍

**Comment by christophercr** [comment]
Closing this since the filtering support was released in 0.1.8 ;)
