### ISSUE TITLE
'createMiddleware' not found

### ISSUE THREAD

**Issue by tsawan** [btroncone/ngrx-store-logger#2]
I just tried to use it and am getting "Object doesn't support property or method 'createMiddleware'". 
I also read a pull-request on @ngrx/store and there are some suggested changes in store to refactore middleware. So is it working spending time to use logger as is?

**Comment by btroncone** [comment]
What version of ngrx/store are you using? The `createMiddleware` method was added in 1.3.3 (I believe).  If it can't be found this would appear to be the issue.

**Comment by tsawan** [comment]
sorry, I am using 1.3.2.
still, is it ok to use it (keeping in mind the discussion to refactor middleware in @ngrx/store)?

**Comment by btroncone** [comment]
It is fine to use. If those changes go through this middleware will still exist, it will just be applied slightly different on application bootstrap.

**Comment by btroncone** [comment]
I am going to close this issue for now. Please let me know if you have any additional concerns. :)

**Comment by tsawan** [comment]
now it's working but in IE 11, it's logging like
 %c prev state color: #9E9E9E; font-weight: bold.

Does it only work in chrome?

**Comment by btroncone** [comment]
My apologies, I have only tested in chrome. When I have some time I will look into support for other browsers.
