### ISSUE TITLE
ngrx4 compatibility?

### ISSUE THREAD

**Issue by bertrandg** [btroncone/ngrx-store-logger#21]
hi,
It doesn't seems to work with latest ngrx 4, am I adding it wrongly or any plan to upgrade it?

I find this logger really useful!

**Comment by pgrm** [comment]
https://github.com/ngrx/platform/issues/170#issuecomment-318031101

**Comment by phra** [comment]
@btroncone can you please align the package.json peer dependecy in order to avoid problem when working with the last version of ngrx?

i've opened #22 

```
╭─phra at kali in /home/phra/git/bloqwallet (refactor/redux ●9✚2)
╰─λ yarn run commit;                                                                                                                                             0 < 18:01:24
yarn run v0.27.5
$ yarn; yarn run validate; yarn run lint
warning fsevents@1.1.2: The platform "linux" is incompatible with this module.
error "ngrx-store-logger#@ngrx/store@^2.2.1" doesn't satisfy found match of "@ngrx/store@4.0.2"
warning "@angular/cli#rxjs@^5.4.2" could be deduped from "5.4.3" to "rxjs@5.4.3"
error Found 1 errors.
error Command failed with exit code 1.
 ```

**Comment by phra** [comment]
@btroncone i suggest to update the README with the comment cited before and close this issue! :rocket:

**Comment by btroncone** [comment]
README has been updated and next version has been published. Sorry for delay, I thought I had closed this earlier.

**Comment by phra** [comment]
:rocket:
