### ISSUE TITLE
I'm getting "[ts] Generic type 'State<T>' requires 1 type argument(s".

### ISSUE THREAD

**Issue by kailashthakuri** [btroncone/ngrx-store-logger#28]
![ngrx](https://user-images.githubusercontent.com/17194118/39979075-d7f1d200-5763-11e8-8b97-eb3f27ff6a82.PNG)

**Comment by kailashthakuri** [comment]
I got it.

**Comment by SaranVairam** [comment]
hey ,

   i am trying to implement this on our angular application.how to implement it on a component . any examples

**Comment by SaranVairam** [comment]
how you import reducer from the directory './reducers' . and also how it is capturing all the component  logs and printing .how it is working.i am very new to this ngrx store logger . can you please explain how did you implement it in your angular application.

**Comment by SaranVairam** [comment]
@kailashthakuri  , can you please explain the steps what you did to implement this on angular.i have mentioned the issue what i am getting while i am trying to implement this ngrx-store-logger on my angular 7 application
![ngrx-store-logger-issue](https://user-images.githubusercontent.com/48825356/55081914-bdd35080-50c6-11e9-97f3-8012092f6d70.png)


i need  to pass two  parameters state and action in  storemodule.for root my case.how can i implement this
