### ISSUE TITLE
"ngrx-store-logger" has an incompatible peer dependency to "@ngrx/store@7.0.0"

### ISSUE THREAD

**Issue by zw-slime** [btroncone/ngrx-store-logger#34]
ng update @ngrx/store

     Package "ngrx-store-logger" has an incompatible peer dependency to "@ngrx/store" (requires "^4.0.0 || ^5.0.0 || ^6.0.0", would install "7.0.0").

**Comment by btroncone** [comment]
Peer dependency has been bumped to 7.0.0 in the lastest release. :)
