### ISSUE TITLE
Implementing in a angular 7

### ISSUE THREAD

**Issue by SaranVairam** [btroncone/ngrx-store-logger#36]
Hi ,

  i ma new to this  ngrx-store logger . your readme file has the steps only on app.module.ts . how this logging works on entire angular application . my implementation is shown below

reducer and state
i have reducer as well as state as shown on the images

![reducer issue](https://user-images.githubusercontent.com/48825356/54819350-a6105c80-4cc1-11e9-9cdc-1ecf811ac870.png)

but while building i got issue , how can i solve this

![image](https://user-images.githubusercontent.com/48825356/54819272-66e20b80-4cc1-11e9-90e7-edc8492e47a7.png)

could anyone please help on this . or a sample repository link will help me .

Thanks

**Comment by btroncone** [comment]
This should be resolved with the last release.
